spring:
      datasource:
         driver-class-name : com.mysql.jdbc.Driver
         url : jdbc:mysql://localhost:3306/my_db?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
         username : hou
         password : hou
         type : com.alibaba.druid.pool.DruidDataSource
         druid:
              initial-size : 20
              min-idle : 1
              max-active : 500
              max-wait : 60000
              time-between-eviction-runs-millis : 60000
              min-evictable-idle-time-millis : 300000
              max-evictable-idle-time-millis : 300000
      jpa:
         hibernate:
              ddl-auto : update
         database : MYSQL     
      data:
         elasticsearch:
         #cluster-name: #默认为elasticsearch
         #cluster-nodes: 127.0.0.1: #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
             properties:
                path:
                    logs: ./elasticsearch/log #elasticsearch日志存储目录
                    data: ./elasticsearch/data #elasticsearch数据存储目录         
      session:
         store-type:
             none                 

mybatis:
    type-aliases-package : com.marquess.learn.entity
    mapper-locations : classpath:mappers/*.xml 