spring:
      datasource:
         driver-class-name : com.mysql.jdbc.Driver
         url : jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
         username : root
         password : root
         type : com.alibaba.druid.pool.DruidDataSource
         druid:
              initial-size : 20
              min-idle : 1
              max-active : 500
              max-wait : 60000
              time-between-eviction-runs-millis : 60000
              min-evictable-idle-time-millis : 300000
              max-evictable-idle-time-millis : 300000
      jpa:
         hibernate:
              ddl-auto : update
         database : MYSQL     

mybatis:
    typeAliasesPackage : com.marquess.learn.entity
    mapperLocations : classpath:mappers/*.xml 